[Interface]
Address = 192.168.21.77/24
PrivateKey = EGUBhwLP8Cz99oF02Plk5OTDjBw4j2uVXSPeG2leBV4=
DNS = 8.8.8.8
[Peer]
PublicKey = /eQ+TTAklBfFA1J7etPIeMYE0FNF6CBvcG/lenN16yY=
AllowedIPs = 0.0.0.0/0
Endpoint = w4.nimbaha.info:3050